# Data Preprocessing

In [34]:
import pandas as pd
import numpy as np

In [35]:
df = pd.read_csv('data_preprocessing.csv', encoding='UTF-8')
df.shape

(10, 4)

In [36]:
df.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [37]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [38]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [39]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

## Missing Value

In [40]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [41]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

## Categorical Value

### Encoding Independent Variable

In [42]:
# remainder 파라미터는 원핫인코딩에 해당되지 않는 컬럼을 어떻게 할건지 ('passthrough'그냥 두거나, 'drop' 드롭하거나)
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], 
                       remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [43]:
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [44]:
pd.get_dummies(df['Country'])

France  Germany  Spain
0       1        0      0
1       0        0      1
2       0        1      0
3       0        0      1
4       0        1      0
5       1        0      0
6       0        0      1
7       1        0      0
8       0        1      0
9       1        0      0

### Encoding Dependent Variable

In [45]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [46]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

# Split Dataset into Training set and Test set

In [47]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [15]:
X_train.shape

(8, 5)

## Numerical Value

### Normalization(MinMaxScaler)

In [16]:
from sklearn.preprocessing import MinMaxScaler
mms = MinMaxScaler()
X_train[:, 3:] = mms.fit_transform(X_train[:, 3:])
X_test[:, 3:] = mms.transform(X_test[:, 3:])

In [17]:
X_train

array([[0.0, 0.0, 1.0, 0.5120772946859904, 0.11428571428571432],
       [0.0, 1.0, 0.0, 0.5652173913043479, 0.45079365079365075],
       [1.0, 0.0, 0.0, 0.7391304347826089, 0.6857142857142855],
       [0.0, 0.0, 1.0, 0.4782608695652175, 0.37142857142857144],
       [0.0, 0.0, 1.0, 0.0, 0.0],
       [1.0, 0.0, 0.0, 0.9130434782608696, 0.8857142857142857],
       [0.0, 1.0, 0.0, 1.0, 1.0],
       [1.0, 0.0, 0.0, 0.34782608695652173, 0.2857142857142856]],
      dtype=object)

### Standardization

In [32]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
X_train[:, 3:] = ss.fit_transform(X_train[:, 3:])
X_test[:, 3:] = ss.transform(X_test[:, 3:])

In [33]:
X_train

array([[0.0, 0.0, 1.0, -0.19159184384578545, -1.0781259408412425],
       [0.0, 1.0, 0.0, -0.014117293757057777, -0.07013167641635372],
       [1.0, 0.0, 0.0, 0.566708506533324, 0.633562432710455],
       [0.0, 0.0, 1.0, -0.30453019390224867, -0.30786617274297867],
       [0.0, 0.0, 1.0, -1.9018011447007988, -1.420463615551582],
       [1.0, 0.0, 0.0, 1.1475343068237058, 1.232653363453549],
       [0.0, 1.0, 0.0, 1.4379472069688968, 1.5749910381638885],
       [1.0, 0.0, 0.0, -0.7401495441200351, -0.5646194287757332]],
      dtype=object)

# Quiz

slkearn.preprocessing.StandardScaler으로 사용하는 표준화 방식으로 계산한 z값과 직접 계산한 z값을 비교해 보세요.

In [48]:
X_train = pd.DataFrame(X_train)
X_train

0    1    2          3             4
0  0.0  0.0  1.0  38.777778       52000.0
1  0.0  1.0  0.0       40.0  63777.777778
2  1.0  0.0  0.0       44.0       72000.0
3  0.0  0.0  1.0       38.0       61000.0
4  0.0  0.0  1.0       27.0       48000.0
5  1.0  0.0  0.0       48.0       79000.0
6  0.0  1.0  0.0       50.0       83000.0
7  1.0  0.0  0.0       35.0       58000.0

In [49]:
num_columns = X_train.iloc[:,3:5]
num_columns

3             4
0  38.777778       52000.0
1       40.0  63777.777778
2       44.0       72000.0
3       38.0       61000.0
4       27.0       48000.0
5       48.0       79000.0
6       50.0       83000.0
7       35.0       58000.0

In [50]:
num_columns.apply(lambda x : (x - np.mean(x)) / np.std(x))

3         4
0 -0.191592 -1.078126
1 -0.014117 -0.070132
2  0.566709  0.633562
3  -0.30453 -0.307866
4 -1.901801 -1.420464
5  1.147534  1.232653
6  1.437947  1.574991
7  -0.74015 -0.564619

- 계산으로 구한 수치형 컬럼의 z값은 StandardScaler로 구한 값과 동일함